### ISSUE TITLE
Breh Where the CCCCrap is the Capital Letters Support Smh 🙄 🙄 🙄 🙄 

### ISSUE THREAD

**Issue by longwatermelon** [interesting84/Ceaser-Ciphers#1]
Lawl Capital Letters Segregation Amirite Gamerz lmFpaoooooooooooooo 😂 👌 😂 👌

**Comment by longwatermelon** [comment]
Bruh Cant believe IAm Being Ignored Smh Ignorant Kids these days 🙄 🙄 🙄 🙄 🙄 🙄 🙄 🙄 🙄 🙄 🙄 🙄 🙄 🙄 🙄 🙄 🙄 🙄

**Comment by interesting84** [comment]
breh do u have like notifs on or  some crap how the frik did u even notice

**Comment by interesting84** [comment]
and what the frik is capital letter segregation brah

**Comment by interesting84** [comment]
lmfao i thought that was some super fancy programming term woops silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄 silly me  😄

**Comment by interesting84** [comment]
dont worry my dedicated fan i will add capital letter support in the next update

**Comment by longwatermelon** [comment]
Yeah You better fix this issue Right this Moment Young Man 😡 😡 😡

**Comment by interesting84** [comment]
brah ok maybe later

**Comment by longwatermelon** [comment]
Bruh U need to Prioritize Ur Needs Bruh 🙄 Dont u know segregation is a Real Thing Smh

**Comment by interesting84** [comment]
bbbbbbreh says the one with like 5 unfinished projects lawl yea ythats right I looked at ur profile

**Comment by interesting84** [comment]
and how the frik did u even know I posted smtg do u have like frikin notifs on or smtg

**Comment by longwatermelon** [comment]
Breh all my projects are finished except for my earliest ones like tetris LMfapooooooo but im not going back and touching java

**Comment by longwatermelon** [comment]
ALso YKnow you get notifications from people you follow posting repos

**Comment by longwatermelon** [comment]
Im not entirely sure if you get like a fricking Email or something but i know for a fact you can definitely see the people you follow post when you open up the github website

**Comment by interesting84** [comment]
lawl what abt mango script and peanut fps and watermelon smsHAHAHHAHAHAHAHHAHAHAHHAHAHAHHAHAHAHAHHAAHAHHHAHAHHAHAH LLLLLLLLLLLAAAAAAAAAWWWWWLLLLLLLLLLLL

**Comment by longwatermelon** [comment]
Bruh those are finished projects Lmfapooooooooooo Do you expect me to make peanut fps the same quality level as unreal engine or some Crap ive just finished my last bug fix a few days ago and now everything renders Perfectly Lmfapooooooooooooooo watermelon sms is already a pretty complete project on its own its already a step above asio-chatroom since it has a full and working gui system with an Actual Interactive Text Box for Chatting and ive polished the looks as much as my Lack of Aesthetic Taste can ANd Mangoscript is a deleted repository and was only created because it was gonna be a group project between me and sid Lmfapooooooooooooooo but he gave up

**Comment by interesting84** [comment]
AH
WELL THEN

**Comment by longwatermelon** [comment]
LMfapooooooooooooooooooo you meant peanut fps not peanut engine but YKnow we shortly realized 3d collisions were too complex for our math levels so we were forced to drop the project

**Comment by interesting84** [comment]
I SEE

**Comment by longwatermelon** [comment]
Perhaps Another Day

**Comment by interesting84** [comment]
lmfapopopopopop

**Comment by longwatermelon** [comment]
Bruh do you have your experiment.html file still i need that

**Comment by longwatermelon** [comment]
Can you send it here Lmfapoooooooooooooooooooo

**Comment by interesting84** [comment]
lmfao ill just do it thru gmail

**Comment by longwatermelon** [comment]
K UwU

**Comment by longwatermelon** [comment]
Bruh, I cannot believe the Audiacity of You to Not fix this issue, Where is the fix I asked for???????????????? Cuz I dont SEE IT HUHHHHHHHHHHHH/????????????????????????? 😠 😠 😠

**Comment by interesting84** [comment]
brih im not a frikin proffesional software developer ok  so I suggest u change ur tone young man You Do Not Want To See Me Cross man the young Wippersnappers these days So Impatient

**Comment by longwatermelon** [comment]
Youg Man You BBetter Change your Tone this Right Instant OR else Iam going to have to Bring out the Big Guns

**Comment by interesting84** [comment]
calling in the cavalry

**Comment by longwatermelon** [comment]
Bruh Be prepared to get Absolutely Smoked Lmfaoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by longwatermelon** [comment]
You were doomed the Moment you talked back to me with That 13 year old Attitude Smh

**Comment by interesting84** [comment]
all these Youngsters With Their Newfangled technology What The Frik Happened To This Generation Back In My Day Elders Were REspected these Wippersnappers WOnt even Know How TO Light A FIre Without THis THang Called Joojle Whatever happened to playing In the woods

**Comment by interesting84** [comment]
And Frolicking In The Meadows

**Comment by interesting84** [comment]
I suggest YOu Brace Yourself as I am GOing to Utterly PUlverise You INto the Oblivion Prepare for hellfire

**Comment by Ay-355** [comment]
what an interesting fight, haha see what i did there

**Comment by interesting84** [comment]
HAHAHHAHAHHAHAHAHAHAHA THAT WAS SO FUNNY I AM EJECTING BROWNIES INTO MY PANTS

**Comment by Ay-355** [comment]
no you

**Comment by Ay-355** [comment]
gottem amrite gamers

**Comment by longwatermelon** [comment]
Bruh Not another Youngster Hippie Child Entering the Fray of Adult Topics 🙄 🙄 Get Outta Here Kid

**Comment by interesting84** [comment]
EGGS DEEEEE

**Comment by Ay-355** [comment]
wat

**Comment by longwatermelon** [comment]
UwU

**Comment by longwatermelon** [comment]
So When are you gonna Fix the Issue Punk

**Comment by longwatermelon** [comment]
If you dont fix the Issue Soon Me and You are gonna Have some Problems lemme Tell you That

**Comment by interesting84** [comment]
Brah j ran into the weirdest error so maybe later

**Comment by Ay-355** [comment]
UwU

**Comment by longwatermelon** [comment]
Bruh An error does not Excuse you from discriminating against capital letters, smh 🙄 🙄 stop making excuses and Fix the issue already 🙄 🙄 🙄 🙄

**Comment by longwatermelon** [comment]
@interesting84

**Comment by longwatermelon** [comment]
Just felt like Pinging you

**Comment by interesting84** [comment]
bbbbreh jus t check hg pls i need help i think i might die

**Comment by interesting84** [comment]
@longwatermelon

**Comment by interesting84** [comment]
punk

**Comment by interesting84** [comment]
lawl imahinr if i close the issue

**Comment by interesting84** [comment]
that would eb real saad now woudnt it

**Comment by Ay-355** [comment]
would it tho?

**Comment by longwatermelon** [comment]
UwU It would @Ay-355

**Comment by interesting84** [comment]
> UwU It would @Ay-355

breh @longwatermelon chcek ur gmail pls punk

**Comment by longwatermelon** [comment]
Brahhhhhhhhhhh Wut

**Comment by longwatermelon** [comment]
LOLLLLLLLLLLLLL- 💆‍♀️ 🏃‍♀️ 😹 👌 😹 👌 ⚰️

**Comment by longwatermelon** [comment]
K i just submitted a pr you better accept this Lmfapoooooooooooooooo

**Comment by longwatermelon** [comment]
K well now the issue is over since i fixed it SMH Cant believe you guys didnt do a single thing 🙄 🙄
